In [1]:
import numpy as np

# Tensor

## Scalar

Hamid: What is the temperature in Houston?

Alexa: 99 degree F

In [4]:
T = np.array(99)
print(f"T is {T} and it has a dimention {T.ndim}")

T is 99 and it has a dimention 0


## Vectors

In [45]:
# Vertical vector - column vector
np.random.seed(5)
vec = np.random.randint(1,10, (2,))
print(vec)

[4 7]


### Rank of a Vector

In [41]:
print(f"The rank of or the number of axis of vec is {vec.ndim}.")

# Retrieve number 7 from vec
print(f"The number sitting at index 1 is {vec[1]}.")

The rank of or the number of axis of vec is 1.
The number sitting at index 1 is 7.


### Linear Combination

In [59]:
i = np.array([1,0]) # unit vector along the x axis
j = np.array([0,1]) # unit vector along the y axis

veccombo = (4*i) + (7*j)
print(veccombo)

[4 7]


# Tensor Operations

add contents here

### Broadcasting

### Elementwise Ops

#### Addition

All arithmetic operatiosn are done element-wise.

In [18]:
# python way
values = [1,2,3,4,5]

for i in range(len(values)):
    values[i] += 10
print(f"Scalar addition to a matrix the python way: {values}")


# vectorized fashion
values_vec = np.array([1,2,3,4,5])
result = values_vec + 10
print(f"Scalar addition to a matrix vectorized way: {result}")

Scalar addition to a matrix the python way: [11, 12, 13, 14, 15]
Scalar addition to a matrix vectorized way: [11 12 13 14 15]


### Normalization

### Dot Product

### Matrix Product

Explain why matrix product of matrices with wrong dimension will not work using the dot product arguments.


NumPy's dot function
You may sometimes see NumPy's dot function in places where you would expect a matmul. It turns out that the results of dot and matmul are the same if the matrices are two dimensional.


Explain why matrix transpose is important in NN.

- data in rows vs data in columns


In [20]:
inputs = np.array([[-0.27,  0.45,  0.64, 0.31]])
inputs, inputs.shape

(array([[-0.27,  0.45,  0.64,  0.31]]), (1, 4))

In [21]:
weights = np.array([[0.02, 0.001, -0.03, 0.036], \
    [0.04, -0.003, 0.025, 0.009], [0.012, -0.045, 0.28, -0.067]])

In [22]:
weights, weights.shape

(array([[ 0.02 ,  0.001, -0.03 ,  0.036],
        [ 0.04 , -0.003,  0.025,  0.009],
        [ 0.012, -0.045,  0.28 , -0.067]]),
 (3, 4))

In [23]:
np.matmul(inputs, weights.T)

array([[-0.01299,  0.00664,  0.13494]])

In [25]:
np.dot(weights, inputs.T)

array([[-0.01299],
       [ 0.00664],
       [ 0.13494]])

# Norm of a Vector

In [2]:
# Dotting a vector with itself
v = np.array([3,4])

sqr_norm = np.dot(v,v) # square norm
np.sqrt(sqr_norm) # norm

array([3, 4])

Messing around